### ISSUE TITLE
Metadata not being cached?

### ISSUE THREAD

**Issue by tacman** [antishov/StofDoctrineExtensionsBundle#10]
I'm noticing that the meta-data never seems to come from the cache, but is saved.

![image](https://user-images.githubusercontent.com/619585/70198795-dd9f2780-16dd-11ea-8fa6-4070ae06e275.png)

Latest stable version of everything, redis cache.
```
    Redis:
        class: Redis
        calls:
            - method: connect
              arguments:
                  - '%env(REDIS_HOST)%'
                  - 6379

    Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
        arguments:
            - '@Redis'
```

Pretty basic config:

```yaml
# Read the documentation: https://symfony.com/doc/current/bundles/StofDoctrineExtensionsBundle/index.html
# See the official DoctrineExtensions documentation for more details: https://github.com/Atlantic18/DoctrineExtensions/tree/master/doc/
stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            tree: false
            timestampable: true
            sluggable: true
```

Just some slugs and timestamps:

```php
    /**
     * @var string $slug
     *
     * @ORM\Column(name="slug", type="string", length=255)
     * @Gedmo\Slug(fields={"name"})
     */
    private $slug;
```

Refreshing the page shows unsuccessful attempts to re-fetch these, then re-saving successfully.  Not urgent (everything works, and is probably cached properly in prod), but seems odd.
